name: Docker Image CI
on: [push]

jobs:
  build:
    uses: chrisns/.github/.github/workflows/dockerbuild.yml@d80df3e4176f3dad3ce8564c71ab95bde5a3425b # main
    with:
      platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
    secrets:
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

