name: Docker Image CI
on: [push]

jobs:
  build:
    uses: chrisns/.github/.github/workflows/dockerbuild.yml@3489b4ea71198d7ab4da58e54cd741ed1c0a86dd # main
    with:
      platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
    secrets:
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

